### ISSUE TITLE
Basic HTTP authentication prevents using the menu

### ISSUE THREAD

**Issue by Komonyi** [Morikko/sync-tab-groups#76] opened 2018-02-15 15:44 UTC
Hi all!

I have a webpage where there is a basic HTTP authentication. I had this window opened when I started to use this extension. When I tried to open the extension menu, the authentication window popped up requesting for my credentials. No matter if I put in the right data or not, the menu gets closed. If I open it again, the authentication window pops up again.

I tried closing the tab with the mentioned webpage, didn't help. It was also saved as a bookmark, deleted that too, still not working. Tried to log in to that page before using the menu, didn't help either. Tried closing FF, open just the default tab alone, still doesn't work.

So currently I am unable to use the menu for this extension, because the authentication window pops up every time, no matter what I do.

Thanks!
Komonyi

**Comment by Morikko** [comment] 2018-02-15 17:15
1. Can you post a screenshot of this particular authentication window ?
2. Are using other extensions with a menu ? Do the window popup also ?

**Comment by Komonyi** [comment] 2018-02-15 20:19
This authentication method is part of the HTTP standard, so it is the same everywhere and browsers support it by default.
For example go to this site: [https://www.httpwatch.com/httpgallery/authentication/](https://www.httpwatch.com/httpgallery/authentication/) and try out the example.

Yes I have another extension which also has its own menu, that works without an issue.

**Comment by Morikko** [comment] 2018-02-15 22:48
To clarify, all the interface is stored locally by the extension and in no way is using HTTP authentication.

I tried your example and saw the window. However, by doing a cancel, I closed the popup and it never opened again. Neither pop up again when I clicked on the menu of STG.

I will suggest you to try to:
 - Disable the extension and I see if the pop up is coming anyway -> thus the extension would be for nothing
 - Disable all your FF extensions (FF provides an option: reload with modules unactivated) and check
 - Give me a page where you have the problem and where I can reproduce it 

In any case, I am rather confident, STG is not the direct root cause as I never use HTTP authentication. Is it a website you trust ?

**Comment by Morikko** [comment] 2018-03-19 00:05
Also a temporary solution is to block the popup to automatically close.

Steps: 
1. Open a tab with `about:config`
2. Search `ui.popup.disable_autohide`
3. Change to true

WARNING: now for closing ALL popups (this extension, the others, right click context menus...) you have to press escape.

**Closed** 2018-09-19 22:30 UTC
Labels: maybe_fixed, wait_information
