### ISSUE TITLE
Group Display

### ISSUE THREAD

**Issue by time-wizard** [Morikko/sync-tab-groups#37] opened 2017-12-04 15:55 UTC
There should be an option to display group names in alphabetical order. It doesn't look like there is any way to organize them. Also, why do the group names have a number in parenthesis after the name, like (1) or (2)?

**Comment by Morikko** [comment] 2017-12-05 10:46
Duplicate of #7 
Yes, it is planned. I am slowly adding features.

It is the number of tabs inside the group.

**Closed** 2017-12-05 10:46 UTC
Labels: duplicate
