### ISSUE TITLE
Chrome back up functions are not working

### ISSUE THREAD

**Issue by officialmmt** [Morikko/sync-tab-groups#79] opened 2018-02-26 13:28 UTC
synctabgroups-backup-5mins.json download windows showing every 5 min on Chrome 64.0.3282.186 Windows 10 x64 @Morikko

**Comment by Morikko** [comment] 2018-02-27 13:22
The window appears because you have probably set to true in the Chrome Preferences (Downloads section):  `Always ask where to save files`

Contrary to Firefox where I can overwrite this setting, I can't in Chrome.

Notes: 
1. Backup is actually NOT working on chrome now 
2. I will add a new back up function to save in the internal memory of the application to provide a better experience 
3. You can set backup to be less frequent or use the manual button (right click on the icon) to avoid seeing the window too much.

Corrections will be in next release :)

**Closed** 2018-03-02 23:27 UTC
Labels: bug, solved

**Comment by officialmmt** [comment] 2018-03-05 10:27
But it is didn't solved. I getting again and again

**Comment by Morikko** [comment] 2018-03-05 12:03
It is not a bug but the normal behavior. Check the first 2 lines of my previous answer.

> Chrome Preferences (Downloads section): `Always ask where to save files`

Have you checked the option state ?

**Comment by officialmmt** [comment] 2018-03-05 14:39
I am sorry. I read that wrong. Now is works

**Comment by mikhoul** [comment] 2018-05-06 01:34
@Morikko  One question about the internal backup in Chrome could you tell me where the local backup files are located (the path) ? 

It could be useful in case of a crash to know the location of the files to retrieve on my daily backup of my whole computer.

Regards :octocat: 

![GitHub Logo](https://i.imgur.com/AO5KYLc.png)

**Comment by Morikko** [comment] 2018-05-06 22:39
Local backups are managed by your browser. They are saved inside your profile (session) directory in your browser setting folder.
https://superuser.com/questions/507536/where-does-google-chrome-save-localstorage-from-extensions

Usually, if it crashes,you can't find them any more in the application, they are lost...

**Comment by mikhoul** [comment] 2018-05-08 01:39
@Morikko 

> Usually, if it crashes,you can't find them any more in the application, they are lost...

 Since  I ask Chrome to ask me where to save the file before downloading for safety if I use "External Backup" it nag me every 5 minutes to save the files what would be the best way to have a reliable backup of all Groups each 5-10 minutes max ? 

Could you use the **IndexedDB** instead of Local Storage, this way the data of "Sync Tab" would be in their own folder and it would be less prone to corruption and crahs proof too 😉. 

**Source:** https://developers.google.com/web/ilt/pwa/working-with-indexeddb
https://i.imgur.com/kJaVU00.png

Regards :octocat:
