### ISSUE TITLE
Add "Open in New Window"

### ISSUE THREAD

**Issue by nemoyatpeace** [Morikko/sync-tab-groups#25] opened 2017-11-30 06:21 UTC
Maybe this is contrary to your goals, but I'd love the ability to open the group in a new window without closing the current group.  I have multiple workflows that I like to jump between quickly, would be better if I could just use this as a bookmark for all of them.

**Comment by MaximilianKohler** [comment] 2017-11-30 18:52
Yeah this would definitely be nice to have until Mozilla fixes the API as mentioned here: https://github.com/Morikko/sync-tab-groups/issues/11

**Comment by Morikko** [comment] 2017-12-01 10:39
Duplicate of #24.

It is already implemented since the beginning ;). I thought exactly the same, especially as closing/opening can be really heavy.
See the [answer](https://github.com/Morikko/sync-tab-groups/issues/24#issuecomment-347147451).

I will create a doc for showing all features.

**Closed** 2017-12-02 17:30 UTC
