### ISSUE TITLE
backup file location popup keeps returning every 5 min. . 

### ISSUE THREAD

**Issue by Barobrand** [Morikko/sync-tab-groups#72] opened 2018-01-31 14:54 UTC
Hi, jut got 0.5
so far so good.. the menus are a little bit largish but OK.. 
the one thing that is irritating me to no extend is that the where to save the backup file pop up every 5 Min.....
there seems to be no way to actually save a directory name in the addon so that I can have it save to there.  and it also desregards my wish and keeps asking me for the default path.. that you at some time have set up.. in addition to that the intervall seems to be of no interest to the backup tool  I set the tiemframe to 1 / week and it still  asks evey 5 min..
Can you pls doa mini update.? 

many thnx

**Comment by Invvard** [comment] 2018-01-31 19:28
While Morikko is fixing it, there's a setting to disable this feature.
It's above the backup interval checkbox list.

**Comment by Morikko** [comment] 2018-01-31 23:40
Duplicate of #66

**Closed by Morikko** 2018-01-31 23:40 UTC
Labels: duplicate
